name: CI with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Prepare pip cache
      - name: Prepare pip cache folder
        run: mkdir -p ~/.cache/pip

      # Cache dependencies
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-82280f8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # Prime cache step (safe)
      - name: prime-cache-82280f8
        run: |
          echo "Cache hit:"
          echo "${{ steps.cache.outputs.cache-hit }}"
