
name: CI with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Prepare pip cache folder
        run: mkdir -p ~/.cache/pip

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-82280f8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: prime-cache-82280f8
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
name: CI with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Prepare pip cache folder
      - name: Prepare cache folder
        run: mkdir -p ~/.cache/pip

      # 4️⃣ Cache pip dependencies
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-82280f8

      # 5️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # 6️⃣ Prime cache step
      - name: prime-cache-82280f8
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
