name: CI with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Prepare pip cache folder
        run: mkdir -p ~/.cache/pip

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-82280f8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: prime-cache-82280f8
        env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
        run: echo "Cache hit: $CACHE_HIT"
